name: ImplementationGuide Publisher

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main or master branch
  push:
    branches:
      - main
      - master
      - staging
  pull_request:
    branches:
      - main
      - master
      - staging

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-publisher:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # checkout repository with fhir package snapshots
      - name: Checkout packages repository
        uses: actions/checkout@v2
        with:
          repository: BIH-CEI/fhir-packages
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          path: fhir-packages
          lfs: true

      - name: Create symbolic link to package directory
        uses: docker://hl7fhir/ig-publisher-base:latest
        with:
          # Get the latest publisher - don't run the batch script but run the line directly
          args: ln -s ./fhir-packages/packages packages


      - name: Update the image to the latest publisher
        uses: docker://hl7fhir/ig-publisher-base:latest
        with:
          # Get the latest publisher - don't run the batch script but run the line directly
          # args: curl -L https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar -o ./input-cache/publisher.jar --create-dirs
          # Nov 17, 2021 - Don't use latest IG Publisher as it raises a Java Exception
          args: curl -L https://github.com/HL7/fhir-ig-publisher/releases/download/1.1.83/publisher.jar -o ./input-cache/publisher.jar --create-dirs

      - name: Run the IG publisher
        uses: docker://hl7fhir/ig-publisher-base:latest
        with:
          # Workaround for inability of sushi to generate snapshots: untar packages first (using script)
          # Run the publisher - don't run the batch script but run the line directly
          args: ./packages/run_ig_publisher.sh

      # deploy implementation guide to github pages
      - name: Deploy
        if: (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
